### ISSUE TITLE
Simplify query handling for non-HTML formats

### ISSUE THREAD

**Issue by Klortho** [HHS/lodestar#9]
Right now, when submitting a query for a particular format (other than HTML) from the [SPARQL user interface page](http://iddev.nlm.nih.gov/mesh/sparql), it first loads the URL using the `render` q.s. param; i.e. http://iddev.nlm.nih.gov/klortho/servlet/query?query=select+*+where+%7B%3Fs+%3Fp+%3Fo%7D&render=XML&limit=50&offset=0.

This is like a "request" for a particular format, or a "prefetch", because we don't know yet whether or not it will succeed.  If it does succeed, then the lode.js code will redirect to the same URL with the `format` q.s. param set, which executes the query on the server again, and downloads the exact same results.  If the original "render" request fails, then the JS will display an error message.

This design is inefficient: it causes the same SPARQL query to be executed twice. Can't we change it so that the check is done before the initial submission, and then do away with the `render` parameter altogether? This would simplify things considerably, especially because right now lodestar supports both a `render` and a `format` q.s. parameter, that mean *almost* the same thing, and this is very confusing.

**Comment by danizen** [comment]
Design goals for an appropriate response:

* Guide the user (presumed to be a researched/semantic web developer) to understand that the endpoint is /mesh/servlet/query rather than anything else.
* Assure that existing links bookmarks and applications do not break.
* Clean things up to avoid extraneous web reloads.
* Try to design things so that it is easy to see if the user is coming from the API in viewing logs.

My idea for an appropriate response 

* Retain the redirects from /mesh/sparql to /mesh/servlet/query when the format is defined.
* Do not reload /mesh/sparql when a new SPARQL query is entered, have the code submit the request to /mesh/servlet/query or /mesh/sparql directly.
* If the desired rendering is not HTML, have the interface warn the user that they will be redirected to the SPARQL endpoint in a new window, and have an "Never warn me again" checkbox that sets a cookie so that they are no longer warned.
* If the desired rendering is HTML, do more or less what we do now, but do it with one round-trip and a rewrite of the bottom part of the page.
* Use a custom, session dependent request header that we put into our requests from the query page so that the log can clearly distinguish API users of the service.    We use this request header to customize logging, either through a custom log format or a customized log location for API users.

This work will not commence for quite awhile, as it is very far from crucial.

**Comment by Klortho** [comment]
I agree with your strategy -- it sounds good!  The only thing I think you might reconsider is opening the new query in a new window.  If you already have the interstitial warning box, then it's unnecessary. And, if the browser is set to download the format, then they'll end up with annoying extra windows, I think.

**Comment by danizen** [comment]
I think we already do too much opening in new windows.   I use the service now, and I end-up with dozens of windows.   As a user, I would rather have control of that - I won't the option to open in a new window through the normal browser controls.   I don't want browser tabs proliferating willy nilly.

**Comment by Klortho** [comment]
I think we're saying the same thing.

**Comment by danizen** [comment]
Ah.   OK

**Comment by davidanderson3** [comment]
Seeing some inconsistent errors when I request format=JSON or format=RDF/JSON for construct queries. Not sure which one is correct (JSON or RDF/JSON), currently neither works for construct queries in dev. 

* [Error: 406 Not Acceptable: The requested data format is not supported. Must be one of XML, JSON, RDF/XML, TURTLE or N3](http://iddev.nlm.nih.gov/mesh/query?query=prefix%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0Aprefix%20meshv%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0A%0Aconstruct%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0Afrom%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0Awhere%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0A&format=RDF/JSON) format=RDF/JSON from /query
* [Error: You can only render graph queries in either HTML, RDF/XML, RDF/JSON, RDF/N3, or TURTLE format](http://iddev.nlm.nih.gov/mesh/query?query=prefix%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0Aprefix%20meshv%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0A%0Aconstruct%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0Afrom%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0Awhere%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0A&format=JSON) - format=JSON from /query
* [Returns nothing, no error message](http://iddev.nlm.nih.gov/mesh/sparql?query=prefix%20mesh%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0Aprefix%20meshv%3A%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0A%0Aconstruct%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0Afrom%20%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0Awhere%20%7B%0A%20%20%20%20mesh%3AD000001%20meshv%3ApreferredConcept%20%3Fprefcon%20.%0A%20%20%20%20%3Fprefcon%20%3Fp%20%3Fo%20.%0A%7D%0A&format=JSON) - format=JSON from /sparql

Select queries are returning XML when the format is invalid or unspecified. Probably should return error message if invalid, or JSON if unspecified. 

If format=RDF/JSON for a select query, it returns this error, which is wrong: "406 Not Acceptable: The requested data format is not supported. Must be one of XML, JSON, RDF/XML, TURTLE or N3." Valid values should be HTML, XML, CSV, TSV or JSON for a select query at /query. The endpoint /sparql may need a different error, because HTML is not a valid value there.

I wonder if it would be a good idea just to display one error message with valid values for BOTH select and construct queries. That way all the information is conveyed in one error, and you don't have to worry about which kind of query it is.

**Comment by danizen** [comment]
We addressed this in the Sprint 1 release.
